### ISSUE TITLE
Create externs file for djax function

### ISSUE THREAD

**Issue by GaryJones** [beezee/djax#11]
```
/**
 * @fileoverview Externs for jQuery djax plugin
 *
 * @externs
 */

/**
 * @param {string} selector
 * @param {Array.<string>=} exceptions
 * @return {jQuery}
 */
jQuery.prototype.djax = function (selector, exceptions) {};
```

I believe the above, saved into a new file `jquery.djax.externs.js` in your repo, will allow Closure Compiler config blocks on JS files that call `djax()`, to be able to be compiled without losing reference to the function name.

e.g.

```
// ==ClosureCompiler==
// @compilation_level ADVANCED_OPTIMIZATIONS
// @output_file_name foobar-djax.js
// @externs_url http://closure-compiler.googlecode.com/svn/trunk/contrib/externs/jquery-1.7.js
// @externs_url https://raw.github.com/beezee/djax/master/jquery.djax.externs.js
// ==/ClosureCompiler==
// http://closure-compiler.appspot.com/home
```

**Comment by beezee** [comment]
Is this necessary in addition to the ClosureCompiler blocks you've added to the plugin file itself?

**Comment by GaryJones** [comment]
Yes.

In my WordPress plugin, I'm enqueueing two scripts - jquery.djax.js and foobar-djax.js.

The first can be minified correctly with the advanced closure compiler with the block that is currently included. All good.

My foobar-djax.js contains a call to `djax()` - trying to minify this with the advanced closure compiler results in the `djax()` call being dropped, as Google doesn't recognise it as a function name that must change (like the jQuery externs does with all of the standard jQuery functions), as it's defined outside of the file. The closure compiler block in my post above is what I would add to my foobar-djax.js so that, not only are the standard jQuery functions recognised, but the `djax()` function is too.

If I had other jQuery plugins that added new functions, then I could add an `@externs_url` for each of them.

**Comment by beezee** [comment]
Makes sense to me. Just added the file to the repo.
