### ISSUE TITLE
Compatibility with JQuery 1.8.x

### ISSUE THREAD

**Issue by WTVader** [beezee/djax#13]
djax doesn't work properly with jQuery 1.8.x

**Comment by beezee** [comment]
Thanks for the note - I'll try and look into this soon

**Comment by rodoabad** [comment]
Is it being caused by looping through the ids?

**Comment by beezee** [comment]
Thanks for bumping @rodoabad - this turned out to be a _really_ stupid bug that jQuery 1.7 didn't care about. See the fix here (only in jquery.djax.js) - https://github.com/beezee/djax/commit/840ded23b41d732533d9f3a4b62d4334e4d753df#jquery.djax.js

Should be good now.

**Comment by rodoabad** [comment]
Np.
