### ISSUE TITLE
Djax $.get on an image

### ISSUE THREAD

**Issue by orangegirl85** [beezee/djax#41]
Hello,

I can't figure it out why the djax click on an image returns a response like this:
�����JExif��II*���������2�������:���(�����������H������H���������,Photoshop 3.0�8BIM�������H�����H������XICC_PROFILE���HLino��mntrRGB XYZ ���   ��1��acspMSFT����IEC sRGB����������������������-HP  �����������������������������������������������cprt��P���3desc������lwtpt������bkpt�����rXYZ�����gXYZ��,���bXYZ��@���dmnd��T���pdmdd�������vued��L����view������$lumi������meas�����$tech��0���rTRC��<��gTRC��<��bTRC��<��text����Copyright (c) 1998 Hewlett-Packard Company��desc�������sRGB IEC61966-2.1�����������sRGB IEC61966-2.1��������������������������������������������������XYZ �������Q�����XYZ ����������������XYZ ������o���8����XYZ ������b��������XYZ ������$��������desc�������IEC http://www.iec.ch�����������IEC http://www.iec.ch����������������������������������������������desc�������.IEC 61966-2.1 Default RGB colour space - sRGB�����������.IEC 61966-2.1 Default RGB colour space - sRGB����������������������desc�������,Reference
...

On Wordpress it's working well, but I moved to Laravel and this is not working anymore.
Any help, would be appreciated.

Thanks!

**Comment by beezee** [comment]
I'd suspect the target url rather than the image. If you right click and copy link address, then paste into the browser, does it work better? Your app may also be reading some headers off the ajax call and responding differently to the request.

**Comment by orangegirl85** [comment]
Yes, the link is working in the browser.

Response Headers
Accept-Ranges   bytes
Content-Length  212100
Content-Type    image/jpeg
Date    Tue, 03 Jun 2014 18:51:44 GMT
Etag    "104c-33c84-4f5c3106f4c80"
Last-Modified   Sat, 29 Mar 2014 18:34:10 GMT
Server  Apache/2.2.14 (Ubuntu)

Request Headers
Accept  _/_
Accept-Encoding gzip, deflate
Accept-Language en-US,en;q=0.5
Cookie  laravel_session=eyJpdiI6ImZid2h6dkRrRU5KVUx4eWxFZ2dUaWhONEVtTEFNaG1OTkI3RzRvMWMyYUk9IiwidmFsdWUiOiJSK2lKN2RkN2xCVFBEaEpUaTFZN1JoaUZqSDFvVG5WY1NXbFpHaXhhZUNsWUR1elQ3MFlpR2hrdEprbmZMNXY5QXBWVW10NVZNVFBtWWJ6ZDZ6a0NUZz09IiwibWFjIjoiYzNkNDg5NGI1MjQ1NzJjYThkMWU3ZDM0N2ZhZjBiZGFkNGQ3NTAyMzE5NmY5YzA1NGZkODQ3MTM0ZGIxMmJlOSJ9
Host    lori.local
Referer http://lori.local/portfolio/weddings
User-Agent  Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:29.0) Gecko/20100101 Firefox/29.0
X-Requested-With    XMLHttpRequest

**Comment by orangegirl85** [comment]
I solved the issue. You can close this. 
Thanks!
