### ISSUE TITLE
Add credits and version to jquery.djax.js

### ISSUE THREAD

**Issue by GaryJones** [beezee/djax#8]
I'd really like to be able to use djax in a WordPress plugin, but I'd like to see your jQuery plugin file contain:
- credits for the author, including a URL back to this repo
- a version string
- a license indicator (hopefully GPL2 or later)

so that your excellent code can be properly attributed :-)

**Comment by beezee** [comment]
Added, thanks for the compliment! :)

Looking forward to see the WP plugin. If you publish it send me a link and I'll be sure to add it to the examples section of the documentation.
